--Participantes Banco Multiplo que foram incluidos via ROBOT
--Participantes que possuem ao menos um conjunto de contas 00,10,20,40,60,68 diferente de encerrada
--Participantes não titulares de familia
--Participnates não titulares de malote
SELECT DISTINCT p.*
FROM CETIP.V_PARTICIPANTES p
INNER JOIN CETIP.CONTA_PARTICIPANTE cp00 ON p.NUM_ID_ENTIDADE = cp00.NUM_ID_ENTIDADE AND cp00.NUM_ID_TIPO_CONTA = 1 AND cp00.NUM_ID_SITUACAO_CONTA != 4		--Miolo 00
INNER JOIN CETIP.CONTA_PARTICIPANTE cp10 ON p.NUM_ID_ENTIDADE = cp10.NUM_ID_ENTIDADE AND cp10.NUM_ID_TIPO_CONTA = 5 AND cp10.NUM_ID_SITUACAO_CONTA != 4		--Miolo 10
INNER JOIN CETIP.CONTA_PARTICIPANTE cp20 ON p.NUM_ID_ENTIDADE = cp20.NUM_ID_ENTIDADE AND cp20.NUM_ID_TIPO_CONTA = 10 AND cp20.NUM_ID_SITUACAO_CONTA != 4	--Miolo 20
INNER JOIN CETIP.CONTA_PARTICIPANTE cp40 ON p.NUM_ID_ENTIDADE = cp40.NUM_ID_ENTIDADE AND cp40.NUM_ID_TIPO_CONTA = 20 AND cp40.NUM_ID_SITUACAO_CONTA != 4	--Miolo 40
INNER JOIN CETIP.CONTA_PARTICIPANTE cp60 ON p.NUM_ID_ENTIDADE = cp60.NUM_ID_ENTIDADE AND cp60.NUM_ID_TIPO_CONTA = 28 AND cp60.NUM_ID_SITUACAO_CONTA != 4	--Miolo 60
INNER JOIN CETIP.CONTA_PARTICIPANTE cp68 ON p.NUM_ID_ENTIDADE = cp68.NUM_ID_ENTIDADE AND cp68.NUM_ID_TIPO_CONTA = 161 AND cp68.NUM_ID_SITUACAO_CONTA != 4	--Miolo 68
LEFT JOIN CETIP.V_SAP_DADOS_MALOTES_E_MEMBROS m ON p.NUM_ID_ENTIDADE = m.ID_PARTIC_DONO_MALOTE
LEFT JOIN (SELECT DISTINCT NUM_ID_TITULAR AS NUM_ID_TITULAR_FAMILIA FROM CETIP.V_FAMILIA_CONTAS) f ON p.NUM_ID_ENTIDADE = f.NUM_ID_TITULAR_FAMILIA
WHERE
    p.NOM_SIMPLIFICADO_ENTIDADE LIKE 'ROBOT%' AND
    p.NOM_SIMPLIFICADO_ENTIDADE LIKE '%BM%' AND
    p.NOM_SIMPLIFICADO_ENTIDADE <> 'ROBOTBM' AND
    p.NUM_ID_SITUACAO_PARTICIPANTE = 1 AND
    m.ID_PARTIC_DONO_MALOTE IS NULL AND
    f.NUM_ID_TITULAR_FAMILIA IS NULL
ORDER BY p.DAT_ALTERACAO;