SELECT
	c.NUM_ID_ENTIDADE ID,
	pf.NUM_ID_ENTIDADE ID_PF,
	pf.COD_CPF COD_CPF_PF,
	c.NUM_ID_MUNICIPIO NUM_ID_MUNICIPIO_CMT,pf.NUM_ID_MUNICIPIO NUM_ID_MUNICIPIO_PF,
	c.NUM_ID_ESTADO_CIVIL NUM_ID_ESTADO_CIVIL_CMT,pf.NUM_ID_ESTADO_CIVIL NUM_ID_ESTADO_CIVIL_PF,
	c.NUM_ID_TIPO_DOCUMENTO NUM_ID_TIPO_DOCUMENTO_CMT,pf.NUM_ID_TIPO_DOCUMENTO NUM_ID_TIPO_DOCUMENTO_PF,
	c.NUM_ID_ATIVIDADE_PF NUM_ID_ATIVIDAD_CMT,pf.NUM_ID_ATIVIDADE_PF NUM_ID_ATIVIDADE_PF,
	ent_pf.NOME_ENTIDADE      B3_NOME_RAZAO_SOCIAL,
	conta_dono.COD_CONTA_PARTICIPANTE CONTA_DONA_CADASTRO,
	conta_custodiante.COD_CONTA_PARTICIPANTE CONTA_COMITENTE
FROM
	cetip.comitente c,
	cetip.RELACAO rel,
	cetip.PESSOA_FISICA pf,
	CETIP.CONTA_PARTICIPANTE conta_dono,
	CETIP.CONTA_COMITENTE conta_comit,
	CETIP.CONTA_PARTICIPANTE conta_custodiante,
	cetip.ENTIDADE ent_pf
WHERE
	rel.num_id_tipo_relacao = 56
	AND c.NUM_ID_TIPO_INVEST_ESTRANGEIRO = 1
	AND c.num_id_entidade = rel.num_id_entidade_para
	AND pf.num_id_entidade(+) = rel.num_id_entidade
	AND c.IND_COMITENTE_SIMPLIFICADO = 'N'
	AND conta_comit.NUM_ID_ENTIDADE = c.NUM_ID_ENTIDADE
	AND pf.NUM_CONTA_RESP_ATU_DADOS = conta_dono.NUM_CONTA_PARTICIPANTE
	AND conta_comit.NUM_CONTA_PARTICIPANTE = conta_custodiante.NUM_CONTA_PARTICIPANTE
	AND pf.NUM_ID_ENTIDADE = ent_pf.NUM_ID_ENTIDADE
	AND pf.COD_CPF = '293.465.810-42'


UPDATE CETIP.COMITENTE
SET NUM_ID_MUNICIPIO = 99999, NUM_ID_ESTADO_CIVIL = 99, NUM_ID_TIPO_DOCUMENTO = 99, NUM_ID_ATIVIDADE_PF = 999
WHERE NUM_ID_ENTIDADE IN
(
    SELECT
	c.NUM_ID_ENTIDADE ID_COMITENTE
FROM
	cetip.comitente c,
	cetip.RELACAO rel,
	cetip.PESSOA_FISICA pf,
	CETIP.CONTA_PARTICIPANTE conta_dono,
	CETIP.CONTA_COMITENTE conta_comit,
	CETIP.CONTA_PARTICIPANTE conta_custodiante
WHERE
	rel.num_id_tipo_relacao = 56
	AND c.NUM_ID_TIPO_INVEST_ESTRANGEIRO = 1
	AND c.num_id_entidade = rel.num_id_entidade_para
	AND pf.num_id_entidade(+) = rel.num_id_entidade
	AND c.IND_COMITENTE_SIMPLIFICADO = 'N'
	AND conta_comit.NUM_ID_ENTIDADE = c.NUM_ID_ENTIDADE
	AND pf.NUM_CONTA_RESP_ATU_DADOS = conta_dono.NUM_CONTA_PARTICIPANTE
	AND conta_comit.NUM_CONTA_PARTICIPANTE = conta_custodiante.NUM_CONTA_PARTICIPANTE
	AND pf.COD_CPF = '431.206.587-07'
)

UPDATE cetip.PESSOA_FISICA
SET NUM_ID_MUNICIPIO = 99999, NUM_ID_ESTADO_CIVIL = 99, NUM_ID_TIPO_DOCUMENTO = 99, NUM_ID_ATIVIDADE_PF = 999
WHERE NUM_ID_ENTIDADE IN
(
    SELECT
	pf.NUM_ID_ENTIDADE ID_PF
FROM
	cetip.comitente c,
	cetip.RELACAO rel,
	cetip.PESSOA_FISICA pf,
	CETIP.CONTA_PARTICIPANTE conta_dono,
	CETIP.CONTA_COMITENTE conta_comit,
	CETIP.CONTA_PARTICIPANTE conta_custodiante
WHERE
	rel.num_id_tipo_relacao = 56
	AND c.NUM_ID_TIPO_INVEST_ESTRANGEIRO = 1
	AND c.num_id_entidade = rel.num_id_entidade_para
	AND pf.num_id_entidade(+) = rel.num_id_entidade
	AND c.IND_COMITENTE_SIMPLIFICADO = 'N'
	AND conta_comit.NUM_ID_ENTIDADE = c.NUM_ID_ENTIDADE
	AND pf.NUM_CONTA_RESP_ATU_DADOS = conta_dono.NUM_CONTA_PARTICIPANTE
	AND conta_comit.NUM_CONTA_PARTICIPANTE = conta_custodiante.NUM_CONTA_PARTICIPANTE
	AND pf.COD_CPF = '385.261.097-40'
)


UPDATE CETIP.ENTIDADE
SET NOME_ENTIDADE = 'Teste Nome Inválido 123'
WHERE NUM_ID_ENTIDADE IN
(
    SELECT
	pf.NUM_ID_ENTIDADE ID_PF
FROM
	cetip.comitente c,
	cetip.RELACAO rel,
	cetip.PESSOA_FISICA pf,
	CETIP.CONTA_PARTICIPANTE conta_dono,
	CETIP.CONTA_COMITENTE conta_comit,
	CETIP.CONTA_PARTICIPANTE conta_custodiante
WHERE
	rel.num_id_tipo_relacao = 56
	AND c.NUM_ID_TIPO_INVEST_ESTRANGEIRO = 1
	AND c.num_id_entidade = rel.num_id_entidade_para
	AND pf.num_id_entidade(+) = rel.num_id_entidade
	AND c.IND_COMITENTE_SIMPLIFICADO = 'N'
	AND conta_comit.NUM_ID_ENTIDADE = c.NUM_ID_ENTIDADE
	AND pf.NUM_CONTA_RESP_ATU_DADOS = conta_dono.NUM_CONTA_PARTICIPANTE
	AND conta_comit.NUM_CONTA_PARTICIPANTE = conta_custodiante.NUM_CONTA_PARTICIPANTE
	AND pf.COD_CPF = '293.465.810-42'
)