    
SELECT TXT_XML_PARAMETROS,DAT_ULTIMO_ENVIO 
FROM cetip.SERVICO_EMAIL se 
WHERE NUM_ID_SERVICO =29597
AND TXT_XML_PARAMETROS  LIKE '%prestador-patricia.melo@b3.com.br%'
AND TO_CHAR(DAT_INCLUSAO,'DD/MM/YYYY')= TO_CHAR(SYSDATE,'DD/MM/YYYY')
ORDER BY DAT_ULTIMO_ENVIO DESC