SELECT
	c.NUM_ID_ENTIDADE ID,
	pf.COD_CPF COD_CPF_PF,
	--c.COD_SEXO COD_SEXO_COMIT,
	pf.COD_SEXO COD_SEXO_PF,
	--c.NOME_PAI NOM_PAI_COMIT,
	pf.NOM_PAI NOM_PAI_PF,
	--c.NUM_ID_MUNICIPIO NUM_ID_MUNICIPIO_COMIT,
	pf.NUM_ID_MUNICIPIO NUM_ID_MUNICIPIO_PF,
	--c.NUM_ID_ESTADO_CIVIL ESTADO_CIVIL_COMIT,
	pf.NUM_ID_ESTADO_CIVIL ESTADO_CIVIL_PF,
	--c.NUM_ID_TIPO_DOCUMENTO TIPO_DOCUMENTO_COMIT,
	pf.NUM_ID_TIPO_DOCUMENTO TIPO_DOCUMENTO_PF,
	--c.COD_DOCUMENTO_IDENTIDADE DOCUMENTO_IDENTIDADE_COMIT,
	pf.COD_DOC_IDENTIDADE DOCUMENTO_IDENTIDADE_PF,
	--c.NOM_ORGAO_EXPEDIDOR NOM_ORGAO_EXPEDIDOR_COMIT,
	pf.NOM_ORGAO_EXPEDIDOR NOM_ORGAO_EXPEDIDOR_PF,
	--c.DATA_EMISSAO_DOCUMENTO_IDENTID DAT_EMISSAO_DOC_IDENTIDADE_COMIT,
	pf.DAT_EMISSAO_DOC_IDENTIDADE DAT_EMISSAO_DOC_IDENTIDADE_PF,
	--c.NUM_ID_ATIVIDADE_PF ATIVIDADE_COMIT,
	pf.NUM_ID_ATIVIDADE_PF ATIVIDADE_PF,
	--c.IND_PESSOA_POLITICAMENTE_EXPOS PPE_COMIT,
	pf.IND_PPE PPE_PF,
	entc.NOME_ENTIDADE NOME_SOCIAL_COMIT,
	pf.NOME_SOCIAL NOME_SOCIAL_PF,
	pf.NUM_ID_ENTIDADE ID_PF,
	conta_dono.COD_CONTA_PARTICIPANTE CONTA_DONA_CADASTRO,
	conta_custodiante.COD_CONTA_PARTICIPANTE CONTA_COMITENTE,
	ent_pf.NOME_ENTIDADE NOME_RAZAO_SOCIAL,
	pf.DAT_NASCIMENTO DATA_NASCIMENTO,
	pf.NOM_MAE NOME_MAE
FROM
	cetip.comitente c,
	cetip.RELACAO rel,
	cetip.ENTIDADE ent_pf,
	cetip.ENTIDADE entC,
	cetip.PESSOA_FISICA pf,
	CETIP.CONTA_PARTICIPANTE conta_dono,
	CETIP.CONTA_COMITENTE conta_comit,
	CETIP.CONTA_PARTICIPANTE conta_custodiante
WHERE
	rel.num_id_tipo_relacao = 56
	AND c.NUM_ID_TIPO_INVEST_ESTRANGEIRO = 1
	AND c.num_id_entidade = rel.num_id_entidade_para
	AND pf.num_id_entidade(+) = rel.num_id_entidade
	AND ent_pf.num_id_entidade = rel.num_id_entidade
	AND c.IND_COMITENTE_SIMPLIFICADO = 'N'
	AND entC.NUM_ID_ENTIDADE = c.NUM_ID_ENTIDADE
	AND pf.NUM_CONTA_RESP_ATU_DADOS = conta_dono.NUM_CONTA_PARTICIPANTE
	AND conta_comit.NUM_ID_ENTIDADE = c.NUM_ID_ENTIDADE
	AND pf.NUM_ID_ENTIDADE = ent_pf.NUM_ID_ENTIDADE
	AND conta_comit.NUM_CONTA_PARTICIPANTE = conta_custodiante.NUM_CONTA_PARTICIPANTE
	AND pf.COD_CPF = '092.537.184-04'
	ORDER BY pf.COD_CPF,
	c.NUM_ID_ENTIDADE