--###DESABILITA###################################
UPDATE CETIP.TCTPFEATURE_TOGGLE
SET IND_FTRE_HAB = 'N',
DATA_INIC_VIG_FTRE = To_date('11-10-2022', 'dd/mm/YYYY'),
DATA_FIM_VIG_FTRE = To_date('31-12-2999', 'dd/mm/YYYY')
WHERE cod_ftre_tog = 'CADBLC_SIC21_DONO_CADASTRO';

SELECT IND_FTRE_HAB FROM CETIP.TCTPFEATURE_TOGGLE WHERE cod_ftre_tog = 'CADBLC_SIC21_DONO_CADASTRO';

--###HABILITA###################################
UPDATE CETIP.TCTPFEATURE_TOGGLE
SET IND_FTRE_HAB = 'S',
DATA_INIC_VIG_FTRE = To_date('11-10-2022', 'dd/mm/YYYY'),
DATA_FIM_VIG_FTRE = To_date('31-12-2999', 'dd/mm/YYYY')
WHERE cod_ftre_tog = 'CADBLC_SIC21_DONO_CADASTRO';