name: Robot Framework CI2

on:
   #push:
    #branches: [ "main" ]
   #pull_request:
    #branches: [ "main" ]
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      #python and robotframework setup
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
          cache: 'pip'
          
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
           robot  .
      - name: Upload test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
           name: reports
           path: ${{ github.workspace }}/report

