name: Robot Framework

on:
   #push:
    #branches: [ "main" ]
   #pull_request:
    #branches: [ "main" ]
   workflow_dispatch:

jobs:
   build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.11]  # 3.12, pypy-3.9
        rf-version: [6.0]
        selenium-version: [4.21.0]
        #browser: [firefox, chrome, headlesschrome]  #edge
        browser: [chrome]  #edge
    steps:
    - run: echo ${{ github.event }}
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }} with Robot Framework ${{ matrix.rf-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: latest
      id: setup-chrome
    - run: |
        echo Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }}
        ${{ steps.setup-chrome.outputs.chrome-path }} --version
    #- name: Setup firefox
      #id: setup-firefox
      #uses: browser-actions/setup-firefox@v1
      #with:
        #firefox-version: latest
    #- run: |
        #echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
        #${{ steps.setup-firefox.outputs.firefox-path }} --version
    #- name: Start xvfb
      #run: |
        #export DISPLAY=:99.0
        #Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
    - name: Install dependencies
      if: matrix.python-version != 'pypy-3.7'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Install dependencies for pypy
      if: matrix.python-version == 'pypy-3.9'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install robotstatuschecker>=1.4
        pip install requests robotframework-pabot
    - name: Install Seleninum v${{ matrix.selenium-version }}
      run: |
        pip install --upgrade selenium==${{ matrix.selenium-version }}
    - name: Install RF ${{ matrix.rf-version }}
      run: |
        pip install -U --pre robotframework==${{ matrix.rf-version }}
    - name: Install drivers via selenium-manager
      run: |
        if [[ ${{ matrix.selenium-version }} == '4.20.0' || ${{ matrix.selenium-version }} == '4.21.0' ]]; then
          SELENIUM_MANAGER_EXE=$(python -c 'from selenium.webdriver.common.selenium_manager import SeleniumManager; sm=SeleniumManager(); print(f"{str(sm._get_binary())}")')
        else
          SELENIUM_MANAGER_EXE=$(python -c 'from selenium.webdriver.common.selenium_manager import SeleniumManager; sm=SeleniumManager(); print(f"{str(sm.get_binary())}")')
        fi 
        echo "$SELENIUM_MANAGER_EXE"
        echo "WEBDRIVERPATH=$($SELENIUM_MANAGER_EXE --browser chrome --debug | awk '/INFO[[:space:]]Driver path:/ {print $NF;exit}')" >> "$GITHUB_ENV"
        echo "$WEBDRIVERPATH"
    # Temporarily ignoring pypy execution
    #- name: Run tests with headless Chrome and with PyPy
      #if: startsWith( matrix.python-version, 'pypy') == true
      #run: |
        #robot ./cadastro/nome/progressivo/CADBLC-1764/TC_AlteracaoIntituicaoFinanceira_NaoEnviaContaB3i.robot
    #- name: Run tests with headless Chrome and with PyPy
      #if: startsWith( matrix.python-version, 'pypy') == true
      #run: |   
        #robot ./cadastro/nome/progressivo/CADBLC-1764/TC_AlteracaoIntituicaoFinanceira_NaoEnviaContaB3i.robot
    - name: Run robot tests
      run: |
         python -m robot -N 'Progressivo: Alteração Dados Participante' -d ./cadastro/nome/progressivo/CADBLC-1764/Resultados/NaoGeraEvento -i PROGRESSIVO_FILA_EVENTO_PARTICIPANTE_NAO_GERA_EVENTO ./cadastro/nome/progressivo/CADBLC-1764
    #- name: publish test results
      #uses: actions/upload-artifact@v1
      #with:
          #name: report
          #path: ./cadastro/nome/progressivo/CADBLC-1764/outut.html
   
 
